import streamlit as st
from services.gemini_service import GeminiService

def render(gemini_service: GeminiService):
    """
    Renders the Learn Concepts page. Allows students to select subjects,
    choose or type topics, and read structured explanations generated by Gemini AI.
    """
    st.markdown(
        '<h1>📚 Learn <span class="gradient-text">Concepts</span></h1>', 
        unsafe_allow_html=True
    )
    st.write(
        "Master technical and logical concepts for campus placements. "
        "DhanushaBuddy explains each topic with definitions, analogies, examples, and interview prep questions."
    )
    st.markdown("---")

    # 1. Subject list (exactly matching the user requirements)
    subjects = [
        "Java",
        "Python",
        "SQL",
        "DBMS",
        "Operating System",
        "Computer Networks",
        "Object-Oriented Programming",
        "Data Structures",
        "Aptitude",
        "Logical Reasoning"
    ]

    selected_subject = st.selectbox(
        "Choose Subject:",
        options=subjects,
        help="Select a placement prep domain."
    )

    # Subject-specific topic suggestions for autocomplete
    topic_suggestions = {
        "Java": ["Garbage Collection", "Multithreading & Concurrency", "HashMap Internal Working", "Java Exception Hierarchy"],
        "Python": ["Decorators", "Generators & Iterators", "GIL (Global Interpreter Lock)", "List Comprehensions"],
        "SQL": ["Joins & Subqueries", "Indexing & Query Optimization", "Normalization vs Denormalization", "Stored Procedures"],
        "DBMS": ["ACID Properties", "Transactions & Concurrency Control", "Entity-Relationship Diagrams", "CAP Theorem"],
        "Operating System": ["Virtual Memory & Paging", "Process vs Thread", "CPU Scheduling Algorithms", "Deadlocks & Bankers Algorithm"],
        "Computer Networks": ["OSI Model Layers", "TCP/IP vs OSI", "TCP 3-Way Handshake", "HTTP vs HTTPS Protocols"],
        "Object-Oriented Programming": ["Polymorphism", "Encapsulation & Abstraction", "SOLID Principles", "Abstract Classes vs Interfaces"],
        "Data Structures": ["Binary Search Trees", "Graph Traversals (DFS & BFS)", "Stack & Queue Operations", "Trie Data Structure"],
        "Aptitude": ["Percentages & Calculations", "Profit and Loss Equations", "Time and Work formulations", "Probability & Combinations"],
        "Logical Reasoning": ["Syllogisms", "Blood Relations Tree", "Coding-Decoding rules", "Seating Arrangement constraints"]
    }

    suggestions = topic_suggestions.get(selected_subject, ["Custom Topic"])
    
    # Allow choosing from suggestions or entering a custom one
    topic_selection_mode = st.radio(
        "Topic Mode:",
        options=["Choose from list", "Enter custom topic"],
        horizontal=True
    )

    if topic_selection_mode == "Choose from list":
        selected_topic = st.selectbox("Select Topic:", options=suggestions)
    else:
        selected_topic = st.text_input("Enter custom topic:", placeholder="e.g. Memory allocation, Heap vs Stack, etc.")

    # Generate Concept Button
    if st.button("Explain Topic with AI", type="primary"):
        if not selected_topic.strip():
            st.error("Please select or enter a topic to explain.")
            return

        # Trigger Gemini Service
        with st.spinner("DhanushaBuddy is explaining the concept... Please wait."):
            result = gemini_service.get_concept_explanation(selected_subject, selected_topic)

        # Check for errors in service output
        if "error" in result:
            st.error(result["error"])
            if "raw_text" in result and result["raw_text"]:
                st.info("Raw response output from Gemini:")
                st.code(result["raw_text"])
            return

        # Display structured result in clean card layout
        st.success(f"Explanation for **{selected_topic}** ({selected_subject}) ready!")
        
        # 1. Definition Card
        st.markdown(
            f"""
            <div class="glass-card" style="border-left: 5px solid #2563EB;">
                <h4 style="color: #1E3A8A; margin-bottom: 0.5rem;">📖 1. Definition</h4>
                <p style="font-size: 1.05rem; line-height: 1.5; margin: 0;">{result.get('definition', 'No definition provided.')}</p>
            </div>
            """,
            unsafe_allow_html=True
        )

        # 2. Simple Explanation Card
        st.markdown(
            f"""
            <div class="glass-card" style="border-left: 5px solid #3B82F6;">
                <h4 style="color: #1E3A8A; margin-bottom: 0.5rem;">💡 2. Simple Explanation</h4>
                <p style="font-size: 1rem; line-height: 1.6; margin: 0; color: #334155;">{result.get('simple_explanation', 'No explanation provided.')}</p>
            </div>
            """,
            unsafe_allow_html=True
        )

        # 3. Real-life Analogy Card
        st.markdown(
            f"""
            <div class="glass-card" style="border-left: 5px solid #10B981;">
                <h4 style="color: #065F46; margin-bottom: 0.5rem;">🌍 3. Real-Life Analogy</h4>
                <p style="font-size: 1rem; line-height: 1.6; margin: 0; font-style: italic; color: #1F2937;">{result.get('analogy', 'No analogy provided.')}</p>
            </div>
            """,
            unsafe_allow_html=True
        )

        # 4. Example Card
        st.markdown(
            """
            <div class="glass-card" style="border-left: 5px solid #8B5CF6; margin-bottom: 0.5rem;">
                <h4 style="color: #5B21B6; margin-bottom: 0.5rem;">⚙️ 4. Practical Example</h4>
            </div>
            """,
            unsafe_allow_html=True
        )
        example_content = result.get('example', '')
        if "```" in example_content:
            st.markdown(example_content)
        else:
            st.code(example_content, language="python" if selected_subject == "Python" else "java" if selected_subject == "Java" else "text")

        # Two-column layout for Questions and Mistakes
        col1, col2 = st.columns(2)

        with col1:
            # 5. Common Interview Questions
            st.markdown(
                """
                <div class="glass-card" style="border-left: 5px solid #F59E0B; height: 100%;">
                    <h4 style="color: #92400E; margin-bottom: 0.5rem;">❓ 5. Common Interview Questions</h4>
                </div>
                """,
                unsafe_allow_html=True
            )
            questions = result.get('interview_questions', [])
            if questions:
                for q in questions:
                    st.write(f"- {q}")
            else:
                st.write("No interview questions listed.")

        with col2:
            # 6. Common Mistakes
            st.markdown(
                """
                <div class="glass-card" style="border-left: 5px solid #EF4444; height: 100%;">
                    <h4 style="color: #991B1B; margin-bottom: 0.5rem;">⚠️ 6. Common Mistakes to Avoid</h4>
                </div>
                """,
                unsafe_allow_html=True
            )
            mistakes = result.get('common_mistakes', [])
            if mistakes:
                for m in mistakes:
                    st.write(f"- {m}")
            else:
                st.write("No mistakes listed.")

        st.markdown("<br>", unsafe_allow_html=True)

        # 7. Key Points Summary Card
        st.markdown(
            """
            <div class="glass-card" style="border-left: 5px solid #6B7280;">
                <h4 style="color: #374151; margin-bottom: 0.5rem;">📌 7. Key Points Summary</h4>
            </div>
            """,
            unsafe_allow_html=True
        )
        summaries = result.get('summary', [])
        if summaries:
            for s in summaries:
                st.write(f"✔️ {s}")
        else:
            st.write("No summary points provided.")
